// This file was generated by generateLibraryHelp.sci on 06-01-2020 12:06
// This file is released under the 3-clause BSD license. See COPYING-BSD.

tbx_build_help("X2C Audio Library",get_absolute_file_path("build_help.sce"));
